name: banana_fly
description: banana flying game of mmxp
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.10.0
  flutter:
    sdk: flutter

  flame_audio: ^2.1.2
  flame_lottie: ^0.3.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - gameassets/images/
    - gameassets/audio/
    # - assets/images/
  #   - assets/audio/

  fonts:
    - family: Game     
      fonts:
        # - asset: packages/banana_fly/lib/gameassets/fonts/Game.ttf
        # - asset: packages/banana_fly/lib/gameassets/fonts/Game.ttf
        - asset: gameassets/fonts/Game.ttf
